package models;

import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import play.db.jpa.GenericModel;
import flexjson.JSONSerializer;

/**
 * VmdbPersona generated by hbm2java
 */
@Entity
@Table(name = "STDB_GERENCIA")
public class VmdbGerencia extends GenericModel {
	
	@Id
	@GeneratedValue(generator="SEQ_GERENCIA", strategy=GenerationType.SEQUENCE)
	@SequenceGenerator(name="SEQ_GERENCIA", sequenceName="SEQ_GERENCIA", allocationSize=1)
	@Column(name = "CO_GERENCIA")
	private Long coGerencia;
	
	@Column(name = "DE_NOMBRE", nullable = false, length = 100)
	private String deNombre;
	
	@Column(name = "ST_GERENCIA", nullable = false, length = 1)
	private Character stGerencia;
	
	@Column(name = "CO_USUARIO_CREACION", nullable = false, length = 50)
	private String coUsuarioCreacion;
	
	@Column(name = "CO_USUARIO_MODIFICACION", length = 50)
	private String coUsuarioModificacion;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DA_FECHA_CREACION", nullable = false, length = 23)
	private Date daFechaCreacion;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DA_FECHA_MODIFICACION", length = 23)
	private Date daFechaModificacion;		
	
	public VmdbGerencia() {
	}    
	
	public Long getCoGerencia() {
		return coGerencia;
	}

	public void setCoGerencia(Long coGerencia) {
		this.coGerencia = coGerencia;
	}

	public String getDeNombre() {
		return deNombre;
	}

	public void setDeNombre(String deNombre) {
		this.deNombre = deNombre;
	}

	public Character getStGerencia() {
		return stGerencia;
	}

	public void setStGerencia(Character stGerencia) {
		this.stGerencia = stGerencia;
	}

	public String getCoUsuarioCreacion() {
		return coUsuarioCreacion;
	}

	public void setCoUsuarioCreacion(String coUsuarioCreacion) {
		this.coUsuarioCreacion = coUsuarioCreacion;
	}

	public String getCoUsuarioModificacion() {
		return coUsuarioModificacion;
	}

	public void setCoUsuarioModificacion(String coUsuarioModificacion) {
		this.coUsuarioModificacion = coUsuarioModificacion;
	}

	public Date getDaFechaCreacion() {
		return daFechaCreacion;
	}

	public void setDaFechaCreacion(Date daFechaCreacion) {
		this.daFechaCreacion = daFechaCreacion;
	}

	public Date getDaFechaModificacion() {
		return daFechaModificacion;
	}

	public void setDaFechaModificacion(Date daFechaModificacion) {
		this.daFechaModificacion = daFechaModificacion;
	}

	public static List<VmdbGerencia> listGerencia(String nombre) {
    	List<VmdbGerencia> list = VmdbGerencia.find("UPPER(deNombre) like ? and stGerencia = ?  order by deNombre asc", "%"+nombre.toUpperCase()+"%",'1').fetch();
        return list;
    }
	
	public static String eliminar(Long id, String usuario) {
		Map result = new HashMap();
		VmdbGerencia gerencia = VmdbGerencia.findById(id);
		if(gerencia != null){
			gerencia.setStGerencia('0');
			gerencia.setCoUsuarioModificacion(usuario);
			gerencia.setDaFechaModificacion(new Date());
			gerencia.save();
			result.put("status",1);
			result.put("message","La gerencia fue eliminado correctamente!");
		}else{
			result.put("status",0);
			result.put("message","No se puede eliminar");
		}
		JSONSerializer mapeo = new JSONSerializer();		
		return mapeo.serialize(result);
	}
	
	public static Map guardarGerencia(VmdbGerencia gerencia, String usuario) {
		Map result = new HashMap();
		result.put("status", 0);
		result.put("message", "Error on Server");
		if(gerencia.getCoGerencia() == null){
			List<VmdbGerencia> list = VmdbGerencia.find("UPPER(deNombre) = ? and stGerencia = ?",gerencia.getDeNombre().toString().toUpperCase(),'1').fetch();
			if(list.size()>0){
				result.put("status", 3);
				result.put("message", "La gerencia ya esta registrado");
			}else{
				gerencia.setCoUsuarioCreacion(usuario);
				gerencia.setDaFechaCreacion(new Date());
				gerencia.save();
				result.put("status", 1);
				result.put("message", "La gerencia fue guardado correctamente");
			}			
		}else{
			gerencia.setCoUsuarioModificacion(usuario);
			gerencia.setDaFechaModificacion(new Date());
			gerencia.save();
			result.put("status", 2);
			result.put("message", "La gerencia fue actualizado correctamente");
		}		
		return result;
	}
	
}
