package models;

import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import play.db.jpa.GenericModel;

/**
 * VmdbMenu generated by hbm2java
 */
@Entity
@Table(name = "STDB_MENU")
public class VmdbMenu extends GenericModel {

//	@Id
//	@GeneratedValue(strategy=GenerationType.AUTO)
//	@Column(name = "CO_MENU", unique = true, nullable = false, columnDefinition="bigint")
//	
	
	@Id	
	@GeneratedValue(generator="SEQ_MENU", strategy=GenerationType.SEQUENCE)
	@SequenceGenerator(name="SEQ_MENU", sequenceName="SEQ_MENU", allocationSize=1)
	@Column(name="CO_MENU")
	private Long coMenu;
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CO_PADRE")
	private VmdbMenu vmdbMenu;
	@Column(name = "CO_USUARIO_CREACION", nullable = false, length = 50)
	private String coUsuarioCreacion;
	@Column(name = "CO_USUARIO_MODIFICACION", length = 50)
	private String coUsuarioModificacion;
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DA_FECHA_CREACION", nullable = false, length = 23)
	private Date daFechaCreacion;
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DA_FECHA_MODIFICACION", length = 23)
	private Date daFechaModificacion;
	@Column(name = "DE_MENU", nullable = false, length = 50)
	private String deMenu;
	@Column(name = "DE_URL", nullable = false, length = 50)
	private String deUrl;
	@Column(name = "ST_MENU", nullable = false, length = 1)
	private Character stMenu;
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "vmdbMenu")
	private Set<VmdbMenu> vmdbMenus = new HashSet<VmdbMenu>(0);
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "vmdbMenu")
	private Set<VmdrRolMenu> vmdrRolMenus = new HashSet<VmdrRolMenu>(0);

	public VmdbMenu() {
	}

	public VmdbMenu(Long coMenu, VmdbMenu vmdbMenu, String coUsuarioCreacion,
			Date daFechaCreacion, String deMenu, String deUrl, Character stMenu) {
		this.coMenu = coMenu;
		this.vmdbMenu = vmdbMenu;
		this.coUsuarioCreacion = coUsuarioCreacion;
		this.daFechaCreacion = daFechaCreacion;
		this.deMenu = deMenu;
		this.deUrl = deUrl;
		this.stMenu = stMenu;
	}

	public VmdbMenu(Long coMenu, VmdbMenu vmdbMenu, String coUsuarioCreacion,
			String coUsuarioModificacion, Date daFechaCreacion,
			Date daFechaModificacion, String deMenu, String deUrl,
			Character stMenu, Set<VmdbMenu> vmdbMenus,
			Set<VmdrRolMenu> vmdrRolMenus) {
		this.coMenu = coMenu;
		this.vmdbMenu = vmdbMenu;
		this.coUsuarioCreacion = coUsuarioCreacion;
		this.coUsuarioModificacion = coUsuarioModificacion;
		this.daFechaCreacion = daFechaCreacion;
		this.daFechaModificacion = daFechaModificacion;
		this.deMenu = deMenu;
		this.deUrl = deUrl;
		this.stMenu = stMenu;
		this.vmdbMenus = vmdbMenus;
		this.vmdrRolMenus = vmdrRolMenus;
	}

	public Long getCoMenu() {
		return coMenu;
	}

	public void setCoMenu(Long coMenu) {
		this.coMenu = coMenu;
	}

	public VmdbMenu getVmdbMenu() {
		return vmdbMenu;
	}

	public void setVmdbMenu(VmdbMenu vmdbMenu) {
		this.vmdbMenu = vmdbMenu;
	}

	public String getCoUsuarioCreacion() {
		return coUsuarioCreacion;
	}

	public void setCoUsuarioCreacion(String coUsuarioCreacion) {
		this.coUsuarioCreacion = coUsuarioCreacion;
	}

	public String getCoUsuarioModificacion() {
		return coUsuarioModificacion;
	}

	public void setCoUsuarioModificacion(String coUsuarioModificacion) {
		this.coUsuarioModificacion = coUsuarioModificacion;
	}

	public Date getDaFechaCreacion() {
		return daFechaCreacion;
	}

	public void setDaFechaCreacion(Date daFechaCreacion) {
		this.daFechaCreacion = daFechaCreacion;
	}

	public Date getDaFechaModificacion() {
		return daFechaModificacion;
	}

	public void setDaFechaModificacion(Date daFechaModificacion) {
		this.daFechaModificacion = daFechaModificacion;
	}

	public String getDeMenu() {
		return deMenu;
	}

	public void setDeMenu(String deMenu) {
		this.deMenu = deMenu;
	}

	public String getDeUrl() {
		return deUrl;
	}

	public void setDeUrl(String deUrl) {
		this.deUrl = deUrl;
	}

	public Character getStMenu() {
		return stMenu;
	}

	public void setStMenu(Character stMenu) {
		this.stMenu = stMenu;
	}

	public Set<VmdbMenu> getVmdbMenus() {
		return vmdbMenus;
	}

	public void setVmdbMenus(Set<VmdbMenu> vmdbMenus) {
		this.vmdbMenus = vmdbMenus;
	}

	public Set<VmdrRolMenu> getVmdrRolMenus() {
		return vmdrRolMenus;
	}

	public void setVmdrRolMenus(Set<VmdrRolMenu> vmdrRolMenus) {
		this.vmdrRolMenus = vmdrRolMenus;
	}

	public static List<VmdbMenu> listMenu() {
    	List<VmdbMenu> list = VmdbMenu.find("stMenu =? and CO_PADRE is null",'1').fetch();
        return list;
    }
	
}
