package models;

import play.*;
import play.db.jpa.*;

import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * VmdbRol generated by hbm2java
 */
@Entity
@Table(name = "STDB_ROL")
public class VmdbRol extends GenericModel {
	
	@Id
	@GeneratedValue(generator="SEQ_ROL", strategy=GenerationType.SEQUENCE)
	@SequenceGenerator(name="SEQ_ROL", sequenceName="SEQ_ROL", allocationSize=1)
	@Column(name = "CO_ROL")
	private Long coRol;
	@Column(name = "CO_USUARIO_CREACION", nullable = false, length = 50)
	private String coUsuarioCreacion;
	@Column(name = "CO_USUARIO_MODIFICACION", length = 50)
	private String coUsuarioModificacion;
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DA_FECHA_CREACION", nullable = false, length = 23)
	private Date daFechaCreacion;
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DA_FECHA_MODIFICACION", length = 23)
	private Date daFechaModificacion;
	@Column(name = "DE_NOMBRE", nullable = false, length = 50)
	private String deNombre;
	@Column(name = "ST_ROL", nullable = false, length = 1)
	private Character stRol;
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "vmdbRol",cascade=CascadeType.ALL)
	private Set<VmdrRolMenu> vmdrRolMenus = new HashSet<VmdrRolMenu>(0);
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "vmdbRol")
	private Set<VmdrUsuarioRol> vmdrUsuarioRols = new HashSet<VmdrUsuarioRol>(0);

	public VmdbRol() {
	}

	public VmdbRol(Long coRol, String coUsuarioCreacion, Date daFechaCreacion, String deNombre, Character stRol) {
		this.coRol = coRol;
		this.coUsuarioCreacion = coUsuarioCreacion;
		this.daFechaCreacion = daFechaCreacion;
		this.deNombre = deNombre;
		this.stRol = stRol;
	}

	public VmdbRol(Long coRol, String coUsuarioCreacion, String coUsuarioModificacion,
			Date daFechaCreacion, Date daFechaModificacion,
			String deNombre, Character stRol,
			Set<VmdrRolMenu> vmdrRolMenus, Set<VmdrUsuarioRol> vmdrUsuarioRols) {
		this.coRol = coRol;
		this.coUsuarioCreacion = coUsuarioCreacion;
		this.coUsuarioModificacion = coUsuarioModificacion;
		this.daFechaCreacion = daFechaCreacion;
		this.daFechaModificacion = daFechaModificacion;
		this.deNombre = deNombre;
		this.stRol = stRol;
		this.vmdrRolMenus = vmdrRolMenus;
		this.vmdrUsuarioRols = vmdrUsuarioRols;
	}

	public Long getCoRol() {
		return coRol;
	}

	public void setCoRol(Long coRol) {
		this.coRol = coRol;
	}

	public String getCoUsuarioCreacion() {
		return coUsuarioCreacion;
	}

	public void setCoUsuarioCreacion(String coUsuarioCreacion) {
		this.coUsuarioCreacion = coUsuarioCreacion;
	}

	public String getCoUsuarioModificacion() {
		return coUsuarioModificacion;
	}

	public void setCoUsuarioModificacion(String coUsuarioModificacion) {
		this.coUsuarioModificacion = coUsuarioModificacion;
	}

	public Date getDaFechaCreacion() {
		return daFechaCreacion;
	}

	public void setDaFechaCreacion(Date daFechaCreacion) {
		this.daFechaCreacion = daFechaCreacion;
	}

	public Date getDaFechaModificacion() {
		return daFechaModificacion;
	}

	public void setDaFechaModificacion(Date daFechaModificacion) {
		this.daFechaModificacion = daFechaModificacion;
	}

	public String getDeNombre() {
		return deNombre;
	}

	public void setDeNombre(String deNombre) {
		this.deNombre = deNombre;
	}

	public Character getStRol() {
		return stRol;
	}

	public void setStRol(Character stRol) {
		this.stRol = stRol;
	}

	public Set<VmdrRolMenu> getVmdrRolMenus() {
		return vmdrRolMenus;
	}

	public void setVmdrRolMenus(Set<VmdrRolMenu> vmdrRolMenus) {
		this.vmdrRolMenus = vmdrRolMenus;
	}

	public Set<VmdrUsuarioRol> getVmdrUsuarioRols() {
		return vmdrUsuarioRols;
	}

	public void setVmdrUsuarioRols(Set<VmdrUsuarioRol> vmdrUsuarioRols) {
		this.vmdrUsuarioRols = vmdrUsuarioRols;
	}
	public static List<VmdbRol> listRol(String nombre) {
    	List<VmdbRol> list = VmdbRol.find("UPPER(deNombre) like ? and stRol =?", "%"+nombre.toUpperCase()+"%",'1').fetch();
        return list;
    }

    public static VmdbRol save(VmdbRol rol) {
        return rol.save();
    }
    
    public static VmdbRol get(Long id){
    	return VmdbRol.findById(id);
    }
}
