package models;

import play.*;
import play.db.jpa.*;

import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * VmdbPersona generated by hbm2java
 */
@Entity
@Table(name = "STDB_TIPO_PERSONA")
public class VmdbTipoPersona extends GenericModel {
	
	@Id
	@GeneratedValue(generator="SEQ_TIPO_PERSONA", strategy=GenerationType.SEQUENCE)
	@SequenceGenerator(name="SEQ_TIPO_PERSONA", sequenceName="SEQ_TIPO_PERSONA", allocationSize=1)
	@Column(name = "CO_TIPO_PERSONA")
	private Long coTipoPersona;
	
	@Column(name = "DE_NOMBRE", nullable = false, length = 150)
	private String deNombre;
	
	@Column(name = "ST_TIPO_PERSONA", nullable = false, length = 1)
	private Character stTipoPersona;
	
	@Column(name = "CO_USUARIO_CREACION", nullable = false, length = 150)
	private String coUsuarioCreacion;
	
	@Column(name = "CO_USUARIO_MODIFICACION", length = 150)
	private String coUsuarioModificacion;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DA_FECHA_CREACION", nullable = false, length = 23)
	private Date daFechaCreacion;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DA_FECHA_MODIFICACION", length = 23)
	private Date daFechaModificacion;
	
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "vmdbTipoPersona")
	private Set<VmdbPersona> vmdbPersonas = new HashSet<VmdbPersona>(0);
	
	public VmdbTipoPersona() {
	}

	public Long getCoTipoPersona() {
		return coTipoPersona;
	}

	public void setCoTipoPersona(Long coTipoPersona) {
		this.coTipoPersona = coTipoPersona;
	}

	public String getCoUsuarioCreacion() {
		return coUsuarioCreacion;
	}

	public void setCoUsuarioCreacion(String coUsuarioCreacion) {
		this.coUsuarioCreacion = coUsuarioCreacion;
	}

	public String getCoUsuarioModificacion() {
		return coUsuarioModificacion;
	}

	public void setCoUsuarioModificacion(String coUsuarioModificacion) {
		this.coUsuarioModificacion = coUsuarioModificacion;
	}

	public Date getDaFechaCreacion() {
		return daFechaCreacion;
	}

	public void setDaFechaCreacion(Date daFechaCreacion) {
		this.daFechaCreacion = daFechaCreacion;
	}

	public Date getDaFechaModificacion() {
		return daFechaModificacion;
	}

	public void setDaFechaModificacion(Date daFechaModificacion) {
		this.daFechaModificacion = daFechaModificacion;
	}

	public String getDeNombre() {
		return deNombre;
	}

	public void setDeNombre(String deNombre) {
		this.deNombre = deNombre;
	}

	public Character getStTipoPersona() {
		return stTipoPersona;
	}

	public void setStTipoPersona(Character stTipoPersona) {
		this.stTipoPersona = stTipoPersona;
	}

	public Set<VmdbPersona> getVmdbPersonas() {
		return vmdbPersonas;
	}

	public void setVmdbPersonas(Set<VmdbPersona> vmdbPersonas) {
		this.vmdbPersonas = vmdbPersonas;
	}
	public static List<VmdbTipoPersona> listTipoPersona(String nombre) {
    	List<VmdbTipoPersona> list = VmdbTipoPersona.find("deNombre like ? and stTipoPersona =?", "%"+nombre+"%",'1').fetch();
        return list;
    }
	
}
