package models;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import play.db.jpa.GenericModel;

/**
 * VmdbPersona generated by hbm2java
 */
@Entity
@Table(name = "STDD_DETALLE_RESERVA")
public class VmdbDetalleReserva extends GenericModel {
	
	@Id
	@GeneratedValue(generator="SEQ_DETALLE_RESERVA", strategy=GenerationType.SEQUENCE)
	@SequenceGenerator(name="SEQ_DETALLE_RESERVA", sequenceName="SEQ_DETALLE_RESERVA", allocationSize=1)
	@Column(name = "CO_DETALLE_RESERVA")
	private Long coDetalleReserva;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CO_RESERVA", nullable = false)
	private VmdbReserva vmdbReserva;
	
	@Column(name = "DE_FECHA", nullable = false, length = 20)
	private String deFecha;
	
	@Column(name = "HORA_DESDE", nullable = false, length = 20)
	private String horaDesde;
	
	@Column(name = "HORA_HASTA", nullable = false, length = 20)
	private String horaHasta;
	
	@Column(name = "ST_DETALLE_RESERVA", nullable = false, length = 1)
	private Character stDetalleReserva;
	
	@Column(name = "ST_ENVIADO", nullable = false, length = 1)
	private Character stEnviado;
	
	@Column(name = "CO_USUARIO_CREACION", nullable = false, length = 50)
	private String coUsuarioCreacion;
	
	@Column(name = "CO_USUARIO_MODIFICACION", length = 50)
	private String coUsuarioModificacion;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DA_FECHA_CREACION", nullable = false, length = 23)
	private Date daFechaCreacion;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DA_FECHA_MODIFICACION", length = 23)
	private Date daFechaModificacion;	
	
	public VmdbDetalleReserva() {
	}		
	
	public Long getCoDetalleReserva() {
		return coDetalleReserva;
	}

	public void setCoDetalleReserva(Long coDetalleReserva) {
		this.coDetalleReserva = coDetalleReserva;
	}

	public VmdbReserva getVmdbReserva() {
		return vmdbReserva;
	}

	public void setVmdbReserva(VmdbReserva vmdbReserva) {
		this.vmdbReserva = vmdbReserva;
	}

	public String getDeFecha() {
		return deFecha;
	}

	public void setDeFecha(String deFecha) {
		this.deFecha = deFecha;
	}

	public String getHoraDesde() {
		return horaDesde;
	}

	public void setHoraDesde(String horaDesde) {
		this.horaDesde = horaDesde;
	}

	public String getHoraHasta() {
		return horaHasta;
	}

	public void setHoraHasta(String horaHasta) {
		this.horaHasta = horaHasta;
	}

	public Character getStDetalleReserva() {
		return stDetalleReserva;
	}

	public void setStDetalleReserva(Character stDetalleReserva) {
		this.stDetalleReserva = stDetalleReserva;
	}
	
	public Character getStEnviado() {
		return stEnviado;
	}

	public void setStEnviado(Character stEnviado) {
		this.stEnviado = stEnviado;
	}

	public String getCoUsuarioCreacion() {
		return coUsuarioCreacion;
	}

	public void setCoUsuarioCreacion(String coUsuarioCreacion) {
		this.coUsuarioCreacion = coUsuarioCreacion;
	}

	public String getCoUsuarioModificacion() {
		return coUsuarioModificacion;
	}

	public void setCoUsuarioModificacion(String coUsuarioModificacion) {
		this.coUsuarioModificacion = coUsuarioModificacion;
	}

	public Date getDaFechaCreacion() {
		return daFechaCreacion;
	}

	public void setDaFechaCreacion(Date daFechaCreacion) {
		this.daFechaCreacion = daFechaCreacion;
	}

	public Date getDaFechaModificacion() {
		return daFechaModificacion;
	}

	public void setDaFechaModificacion(Date daFechaModificacion) {
		this.daFechaModificacion = daFechaModificacion;
	}
	
}
