package models;

import play.*;
import play.db.jpa.*;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * VmdrRolMenu generated by hbm2java
 */
@Entity
@Table(name = "STDR_ROL_MENU")
public class VmdrRolMenu extends GenericModel {

	@Id
	@GeneratedValue(generator="SEQ_ROL_MENU", strategy=GenerationType.SEQUENCE)
	@SequenceGenerator(name="SEQ_ROL_MENU", sequenceName="SEQ_ROL_MENU", allocationSize=1)
	@Column(name = "CO_ROL_MENU")
	private Long coRolMenu;
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CO_MENU", nullable = false)
	private VmdbMenu vmdbMenu;
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CO_ROL", nullable = false)
	private VmdbRol vmdbRol;
	@Column(name = "CO_USUARIO_CREACION", nullable = false, length = 50)
	private String coUsuarioCreacion;
	@Column(name = "CO_USUARIO_MODIFICACION", length = 50)
	private String coUsuarioModificacion;
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DA_FECHA_CREACION", nullable = false, length = 23)
	private Date daFechaCreacion;
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DA_FECHA_MODIFICACION", length = 23)
	private Date daFechaModificacion;
	@Column(name = "ST_ROL_MENU", nullable = false, length = 1)
	private Character stRolMenu;

	public VmdrRolMenu() {
	}

	public VmdrRolMenu(Long coRolMenu, VmdbMenu vmdbMenu, VmdbRol vmdbRol,
			String coUsuarioCreacion, Date daFechaCreacion, Character stRolMenu) {
		this.coRolMenu = coRolMenu;
		this.vmdbMenu = vmdbMenu;
		this.vmdbRol = vmdbRol;
		this.coUsuarioCreacion = coUsuarioCreacion;
		this.daFechaCreacion = daFechaCreacion;
		this.stRolMenu = stRolMenu;
	}

	public VmdrRolMenu(Long coRolMenu, VmdbMenu vmdbMenu, VmdbRol vmdbRol,
			String coUsuarioCreacion, String coUsuarioModificacion,
			Date daFechaCreacion, Date daFechaModificacion, Character stRolMenu) {
		this.coRolMenu = coRolMenu;
		this.vmdbMenu = vmdbMenu;
		this.vmdbRol = vmdbRol;
		this.coUsuarioCreacion = coUsuarioCreacion;
		this.coUsuarioModificacion = coUsuarioModificacion;
		this.daFechaCreacion = daFechaCreacion;
		this.daFechaModificacion = daFechaModificacion;
		this.stRolMenu = stRolMenu;
	}

	public Long getCoRolMenu() {
		return coRolMenu;
	}

	public void setCoRolMenu(Long coRolMenu) {
		this.coRolMenu = coRolMenu;
	}

	public VmdbMenu getVmdbMenu() {
		return vmdbMenu;
	}

	public void setVmdbMenu(VmdbMenu vmdbMenu) {
		this.vmdbMenu = vmdbMenu;
	}

	public VmdbRol getVmdbRol() {
		return vmdbRol;
	}

	public void setVmdbRol(VmdbRol vmdbRol) {
		this.vmdbRol = vmdbRol;
	}

	public String getCoUsuarioCreacion() {
		return coUsuarioCreacion;
	}

	public void setCoUsuarioCreacion(String coUsuarioCreacion) {
		this.coUsuarioCreacion = coUsuarioCreacion;
	}

	public String getCoUsuarioModificacion() {
		return coUsuarioModificacion;
	}

	public void setCoUsuarioModificacion(String coUsuarioModificacion) {
		this.coUsuarioModificacion = coUsuarioModificacion;
	}

	public Date getDaFechaCreacion() {
		return daFechaCreacion;
	}

	public void setDaFechaCreacion(Date daFechaCreacion) {
		this.daFechaCreacion = daFechaCreacion;
	}

	public Date getDaFechaModificacion() {
		return daFechaModificacion;
	}

	public void setDaFechaModificacion(Date daFechaModificacion) {
		this.daFechaModificacion = daFechaModificacion;
	}

	public Character getStRolMenu() {
		return stRolMenu;
	}

	public void setStRolMenu(Character stRolMenu) {
		this.stRolMenu = stRolMenu;
	}
	public static int deletexRol(Long idrol){
    	return VmdrRolMenu.delete("CO_ROL = ?", idrol);
    }
}
