package models;

import play.*;
import play.db.jpa.*;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * VmdrUsuarioRol generated by hbm2java
 */
@Entity
@Table(name = "STDR_USUARIO_ROL")
public class VmdrUsuarioRol extends GenericModel {

	@Id
	@GeneratedValue(generator="SEQ_USUARIO_ROL", strategy=GenerationType.SEQUENCE)
	@SequenceGenerator(name="SEQ_USUARIO_ROL", sequenceName="SEQ_USUARIO_ROL", allocationSize=1)
	@Column(name = "CO_USUARIO_ROL")
	private Long coUsuarioRol;
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CO_USUARIO", nullable = false)
	private VmdbUsuario vmdbUsuario;
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CO_ROL", nullable = false)
	private VmdbRol vmdbRol;
	@Column(name = "CO_USUARIO_CREACION", nullable = false, length = 50)
	private String coUsuarioCreacion;
	@Column(name = "CO_USUARIO_MODIFICACION", length = 50)
	private String coUsuarioModificacion;
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DA_FECHA_CREACION", nullable = false, length = 23)
	private Date daFechaCreacion;
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DA_FECHA_MODIFICACION", length = 23)
	private Date daFechaModificacion;
	@Column(name = "ST_USUARIO_ROL", nullable = false, length = 1)
	private Character stUsuarioRol;

	public VmdrUsuarioRol() {
	}

	public VmdrUsuarioRol(Long coUsuarioRol, VmdbUsuario vmdbUsuario,
			VmdbRol vmdbRol, String coUsuarioCreacion, Date daFechaCreacion,
			Character stUsuarioRol) {
		this.coUsuarioRol = coUsuarioRol;
		this.vmdbUsuario = vmdbUsuario;
		this.vmdbRol = vmdbRol;
		this.coUsuarioCreacion = coUsuarioCreacion;
		this.daFechaCreacion = daFechaCreacion;
		this.stUsuarioRol = stUsuarioRol;
	}

	public VmdrUsuarioRol(Long coUsuarioRol, VmdbUsuario vmdbUsuario,
			VmdbRol vmdbRol, String coUsuarioCreacion,
			String coUsuarioModificacion, Date daFechaCreacion,
			Date daFechaModificacion, Character stUsuarioRol) {
		this.coUsuarioRol = coUsuarioRol;
		this.vmdbUsuario = vmdbUsuario;
		this.vmdbRol = vmdbRol;
		this.coUsuarioCreacion = coUsuarioCreacion;
		this.coUsuarioModificacion = coUsuarioModificacion;
		this.daFechaCreacion = daFechaCreacion;
		this.daFechaModificacion = daFechaModificacion;
		this.stUsuarioRol = stUsuarioRol;
	}

	public Long getCoUsuarioRol() {
		return coUsuarioRol;
	}

	public void setCoUsuarioRol(Long coUsuarioRol) {
		this.coUsuarioRol = coUsuarioRol;
	}

	public VmdbUsuario getVmdbUsuario() {
		return vmdbUsuario;
	}

	public void setVmdbUsuario(VmdbUsuario vmdbUsuario) {
		this.vmdbUsuario = vmdbUsuario;
	}

	public VmdbRol getVmdbRol() {
		return vmdbRol;
	}

	public void setVmdbRol(VmdbRol vmdbRol) {
		this.vmdbRol = vmdbRol;
	}

	public String getCoUsuarioCreacion() {
		return coUsuarioCreacion;
	}

	public void setCoUsuarioCreacion(String coUsuarioCreacion) {
		this.coUsuarioCreacion = coUsuarioCreacion;
	}

	public String getCoUsuarioModificacion() {
		return coUsuarioModificacion;
	}

	public void setCoUsuarioModificacion(String coUsuarioModificacion) {
		this.coUsuarioModificacion = coUsuarioModificacion;
	}

	public Date getDaFechaCreacion() {
		return daFechaCreacion;
	}

	public void setDaFechaCreacion(Date daFechaCreacion) {
		this.daFechaCreacion = daFechaCreacion;
	}

	public Date getDaFechaModificacion() {
		return daFechaModificacion;
	}

	public void setDaFechaModificacion(Date daFechaModificacion) {
		this.daFechaModificacion = daFechaModificacion;
	}

	public Character getStUsuarioRol() {
		return stUsuarioRol;
	}

	public void setStUsuarioRol(Character stUsuarioRol) {
		this.stUsuarioRol = stUsuarioRol;
	}

	public static void deleteRols(Long coUsuario) {
		VmdrUsuarioRol.delete("CO_USUARIO = ? ", coUsuario);		
	}
	
}